"""add name and photo_url to chats

Revision ID: 40b6937e8cee
Revises: ff04ab12b4dd
Create Date: 2026-04-23 17:12:55.209375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "40b6937e8cee"
down_revision: Union[str, Sequence[str], None] = "ff04ab12b4dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats", sa.Column("name", sa.String(length=64), nullable=True)
    )
    op.add_column("chats", sa.Column("photo_url", sa.String(), nullable=True))
    op.add_column("chats", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "chats", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chats", type_="foreignkey")
    op.drop_column("chats", "owner_id")
    op.drop_column("chats", "photo_url")
    op.drop_column("chats", "name")
    # ### end Alembic commands ###
