"""add chat tables

Revision ID: ff04ab12b4dd
Revises: cb125f73b43c
Create Date: 2026-04-21 19:34:16.094101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ff04ab12b4dd"
down_revision: Union[str, Sequence[str], None] = "cb125f73b43c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column(
            "type", sa.Enum("DIRECT", "GROUP", name="chattype"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chats_members",
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "user_id", name="uq_chat_member"),
    )
    op.create_index(
        op.f("ix_chats_members_chat_id"),
        "chats_members",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chats_members_user_id"),
        "chats_members",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "chats_messages",
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chats_messages_author_id"),
        "chats_messages",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chats_messages_chat_id"),
        "chats_messages",
        ["chat_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chats_messages_chat_id"), table_name="chats_messages"
    )
    op.drop_index(
        op.f("ix_chats_messages_author_id"), table_name="chats_messages"
    )
    op.drop_table("chats_messages")
    op.drop_index(op.f("ix_chats_members_user_id"), table_name="chats_members")
    op.drop_index(op.f("ix_chats_members_chat_id"), table_name="chats_members")
    op.drop_table("chats_members")
    op.drop_table("chats")
    # ### end Alembic commands ###
